/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppHome {
    'slidesToShow': number;
  }
  interface AppRoot {}
  interface DottButton {
    'text': string;
  }
  interface DtBook {}
  interface DtCard {
    'header': string;
  }
  interface DtCarousel {
    'books': any[];
    'slidesToShow': number;
  }
  interface DtLangSelector {}
  interface DtSearchBar {
    'lang': string;
  }
  interface TypescriptFn {
    'value': number;
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLDottButtonElement extends Components.DottButton, HTMLStencilElement {}
  var HTMLDottButtonElement: {
    prototype: HTMLDottButtonElement;
    new (): HTMLDottButtonElement;
  };

  interface HTMLDtBookElement extends Components.DtBook, HTMLStencilElement {}
  var HTMLDtBookElement: {
    prototype: HTMLDtBookElement;
    new (): HTMLDtBookElement;
  };

  interface HTMLDtCardElement extends Components.DtCard, HTMLStencilElement {}
  var HTMLDtCardElement: {
    prototype: HTMLDtCardElement;
    new (): HTMLDtCardElement;
  };

  interface HTMLDtCarouselElement extends Components.DtCarousel, HTMLStencilElement {}
  var HTMLDtCarouselElement: {
    prototype: HTMLDtCarouselElement;
    new (): HTMLDtCarouselElement;
  };

  interface HTMLDtLangSelectorElement extends Components.DtLangSelector, HTMLStencilElement {}
  var HTMLDtLangSelectorElement: {
    prototype: HTMLDtLangSelectorElement;
    new (): HTMLDtLangSelectorElement;
  };

  interface HTMLDtSearchBarElement extends Components.DtSearchBar, HTMLStencilElement {}
  var HTMLDtSearchBarElement: {
    prototype: HTMLDtSearchBarElement;
    new (): HTMLDtSearchBarElement;
  };

  interface HTMLTypescriptFnElement extends Components.TypescriptFn, HTMLStencilElement {}
  var HTMLTypescriptFnElement: {
    prototype: HTMLTypescriptFnElement;
    new (): HTMLTypescriptFnElement;
  };
  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'dott-button': HTMLDottButtonElement;
    'dt-book': HTMLDtBookElement;
    'dt-card': HTMLDtCardElement;
    'dt-carousel': HTMLDtCarouselElement;
    'dt-lang-selector': HTMLDtLangSelectorElement;
    'dt-search-bar': HTMLDtSearchBarElement;
    'typescript-fn': HTMLTypescriptFnElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {
    'slidesToShow'?: number;
  }
  interface AppRoot {}
  interface DottButton {
    'text'?: string;
  }
  interface DtBook {}
  interface DtCard {
    'header'?: string;
  }
  interface DtCarousel {
    'books'?: any[];
    'slidesToShow'?: number;
  }
  interface DtLangSelector {
    'onDtDialectChange'?: (event: CustomEvent<any>) => void;
    'onDtLanguageChange'?: (event: CustomEvent<any>) => void;
  }
  interface DtSearchBar {
    'lang'?: string;
    'onDtQueryChange'?: (event: CustomEvent<any>) => void;
  }
  interface TypescriptFn {
    'value'?: number;
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-root': AppRoot;
    'dott-button': DottButton;
    'dt-book': DtBook;
    'dt-card': DtCard;
    'dt-carousel': DtCarousel;
    'dt-lang-selector': DtLangSelector;
    'dt-search-bar': DtSearchBar;
    'typescript-fn': TypescriptFn;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'dott-button': LocalJSX.DottButton & JSXBase.HTMLAttributes<HTMLDottButtonElement>;
      'dt-book': LocalJSX.DtBook & JSXBase.HTMLAttributes<HTMLDtBookElement>;
      'dt-card': LocalJSX.DtCard & JSXBase.HTMLAttributes<HTMLDtCardElement>;
      'dt-carousel': LocalJSX.DtCarousel & JSXBase.HTMLAttributes<HTMLDtCarouselElement>;
      'dt-lang-selector': LocalJSX.DtLangSelector & JSXBase.HTMLAttributes<HTMLDtLangSelectorElement>;
      'dt-search-bar': LocalJSX.DtSearchBar & JSXBase.HTMLAttributes<HTMLDtSearchBarElement>;
      'typescript-fn': LocalJSX.TypescriptFn & JSXBase.HTMLAttributes<HTMLTypescriptFnElement>;
    }
  }
}


